In [1]:
import pandas as pd
import numpy as np
import os
import time
import datetime

In [2]:
def sorteador_pcs(nucleo,num_sorteados,arquivo_csv):
    nucleo = nucleo.upper()
    seed = int(np.random.random()*1000000000)
    np.random.seed(seed)
    
    # Gerando relatório
    writter = open('sorteio-elos-{}-{}.txt'.format(nucleo,datetime.date.today()),'w')
    writter.write('### SORTEIO DE SELEÇÃO {}- ELOS DA EDUCAÇÃO {} \n'.format(nucleo,datetime.date.today().year))
    writter.write('### Realizado em {}'.format(datetime.datetime.now().strftime('%d/%m/%Y às %H/%M')))
    writter.write('\n\n'+'#'*70+'\n\n')
    
    # Importando a tabela do csv
    tabela_notas = pd.read_csv(os.path.join(arquivo_csv),index_col="codigo_aluno")
    writter.write('## NOTAS UTILIZADAS COMO PESOS PARA O SORTEIO ##\n\n' + tabela_notas.to_string())
    writter.write('\n\n'+'#'*70+'\n\n')
    
    # Criando a estrutura de dados
    tabela_notas = pd.read_csv(os.path.join(arquivo_csv),index_col="codigo_aluno")
    tabela_notas.nota = tabela_notas.nota.map(lambda x: float(x.replace(',','.')))
    dic_notas = tabela_notas['nota'].to_dict()
    
    # Preparando os dados pro sorteio
    codigos_alunos = [item[0] for item in list(dic_notas.items())] 
    notas_alunos = [item[1] for item in list(dic_notas.items())]
    notas_normalizadas = [nota/sum(notas_alunos) for nota in notas_alunos] #Normalizando as notas
    
    # Sorteio
    sorteados = list(np.random.choice(a = codigos_alunos, size = num_sorteados, replace=False, p = notas_normalizadas))
    
    # Salvando os classificados
    df_sorteados = pd.DataFrame({'codigo_aluno':sorteados,'ordem_sorteio':range(1,len(sorteados)+1)}).set_index('ordem_sorteio')
    writter.write('## SORTEADOS ##\n\n')
    writter.write(df_sorteados.to_string())
    writter.write('\n\n'+'#'*70+'\n\n')
   
    # Criando tabela de visualização
    visualizacao = {"codigo_aluno": [], "nota": [], "status": []}    
    for codigo in codigos_alunos:
        visualizacao["codigo_aluno"].append(codigo)
        visualizacao["nota"].append(dic_notas[codigo])
        if codigo in sorteados:
            visualizacao["status"].append("Sorteado")
        else:
            visualizacao["status"].append("Nao Sorteado")
    tabela_visualizacao = pd.DataFrame(visualizacao).set_index('codigo_aluno')
    
    writter.write('## RELAÇÃO FINAL DOS CANDIDATOS ##\n\n')
    writter.write(tabela_visualizacao.to_string())
    
    # Exportando visualização
    tabela_visualizacao.to_csv("tabela_resultados_{}.csv".format(nucleo))
    
    # Metodologia
    metodologia = """
    O sorteio foi realizado através de um script em Python, disponível em https://github.com/AliferSales/Sorteador-Elos-da-Educacao.
    
    O script recebe uma tabela com duas colunas: codigo_aluno e nota. O sorteio é realizado entre os códigos dos alunos e é ponderado a partir de suas notas.
    
    Para o sorteio foi escolhido aleatóriamente um seed para o algoritmo de sorteio oferecido pelo pacote numpy.
    O seed é sorteado previamente para fins de revisão do sorteio, de forma que seja conhecido o seed utilizado no sorteio. Isso permite que o sorteio seja totalmente reproduzido.
    
    O seed sorteado foi: {seed}, instanciado pelo comando np.random.seed({seed})
    """.format(seed=seed)
    
    writter.write('\n\n'+'#'*70+'\n\n')
    writter.write('## METODOLOGIA UTILIZADA ##\n\n')
    writter.write(metodologia)
    
    writter.close()
    
    return tabela_visualizacao

In [3]:
sorteador_pcs('EXEMPLO',10,'exemplo.csv')

              nota        status
codigo_aluno
640           4.78  Nao Sorteado
512           5.09      Sorteado
683           4.44  Nao Sorteado
644           4.96  Nao Sorteado
517           4.76  Nao Sorteado
705           4.83  Nao Sorteado
520           4.18  Nao Sorteado
524           5.85  Nao Sorteado
525           5.44  Nao Sorteado
526           4.65  Nao Sorteado
533           6.23  Nao Sorteado
534           5.43  Nao Sorteado
589           4.31  Nao Sorteado
666           4.69  Nao Sorteado
667           6.03  Nao Sorteado
540           6.60  Nao Sorteado
669           4.86  Nao Sorteado
670           5.17  Nao Sorteado
543           6.82      Sorteado
544           4.74  Nao Sorteado
673           5.34  Nao Sorteado
674           6.51  Nao Sorteado
547           5.80  Nao Sorteado
549           5.73  Nao Sorteado
680           4.76      Sorteado
554           5.36  Nao Sorteado
647           4.78  Nao Sorteado
685           5.30  Nao Sorteado
558           5.91      Sorteado
689           5.29  Nao Sorteado
...            ...           ...
706           6.06  Nao Sorteado
580           4.71      Sorteado
584           4.88  Nao Sorteado
585           4.95  Nao Sorteado
586           6.38  Nao Sorteado
715           4.83  Nao Sorteado
546           4.53  Nao Sorteado
718           4.70  Nao Sorteado
653           4.85      Sorteado
593           4.98  Nao Sorteado
654           4.25  Nao Sorteado
729           4.31  Nao Sorteado
605           4.18  Nao Sorteado
606           5.70      Sorteado
607           4.43  Nao Sorteado
610           5.62  Nao Sorteado
507           4.30      Sorteado
612           4.42  Nao Sorteado
613           4.56  Nao Sorteado
619           4.98  Nao Sorteado
621           5.76  Nao Sorteado
624           4.37  Nao Sorteado
625           4.76  Nao Sorteado
626           4.79  Nao Sorteado
632           4.17  Nao Sorteado
634           4.67  Nao Sorteado
639           5.74  Nao Sorteado
509           5.76  Nao Sorteado
638           5.65  Nao Sorteado
511           5.11  Nao Sorteado

[69 rows x 2 columns]